### ISSUE TITLE
Is the Sunlit name and logo open source or owned by Micro.blog ?

### ISSUE THREAD

**Issue by zorn** [microdotblog/sunlit#88]
This is a question I have for my own work but I feel like it's parallels will with Sunlit and Micro.blog (the company) so I'll ask it here too:

> Looking for an example of an open source MIT app that contains trademarked names and logos inside. How do you document the open source nature of the code base but retain the rights to the name / trademark and logo?

https://twitter.com/zorn/status/1298257644470247424

**Comment by manton** [comment]
Good question. I consider the name and logo owned by Micro.blog, but there is no registered trademark. Maybe we need to spell this out in the license? I wanted Sunlit to be MIT specifically so that someone could use the code in a closed-source commercial product if they wanted to, but forking it and re-using the name Sunlit would cause a lot of confusion.

**Comment by manton** [comment]
WordPress seems to have figured this out: https://wordpressfoundation.org/trademark-policy/

**Comment by zorn** [comment]
Here is another resource to check out. 

https://google.github.io/opencasebook/trademarks/

This is all on my "to read" list. No actionable recommendations but wanted to share as I thought aloud.

**Comment by paulrobertlloyd** [comment]
As an aside, always thought it’d be nice if Micro.blog, Sunlit and Wavelength had icons/logos that looked part of the same family.

**Comment by cheesemaker** [comment]
Can we close this now?
